user:
  name:
    min_length: 6
reset_pass_expired_time: 2
carts:
  update_qty_min: 1
  update_qty_max: 10
paginate: 8
order:
  ship_method:
    quick_ship: 1
    normal_ship: 2
  pay_method:
    pay_pal: 1
    pay_money: 2
  status:
    waiting: 0
    confirmed: 1
    delivering: 2
    finish: 3
    cancelled: 4
  payment_status:
    unpaid: 0
    paid: 1
admin_role: 1
